name: Update List of Cool People

on:
  watch:
    types: [started]
  workflow_dispatch:

jobs:
  cool-people:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update README
        run: node cool.js ${{ github.repository }} ${{ github.token }} 6
      - name: Commit changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add --all
          git diff-index --quiet HEAD || git commit -m "Update List of Cool People"
      - name: Pull changes
        run: git pull -r
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
